spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgressql
      database-plataform: org.hibernate.dialect.PostgresSQLDialect